[tool.black]
line-length = 79
target-version = ['py311']

[tool.isort]
profile = "black"
skip_glob = ["**/__init__.py"]
line_length = 79
skip_gitignore = "True"

[tool.pytest.ini_options]
addopts = "--color=yes"
filterwarnings = [
    # TODO: these are probably too restrictive
    'ignore::UserWarning',
    'ignore::DeprecationWarning',
]

[tool.mypy]
exclude = 'mitiq.*.tests*'
ignore_missing_imports = true

# Enable a subset of strict options
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_configs = true
