name: build (master only)

on:
  push:
    branches:
      - master

jobs:

    # runs just the main & benchmarking tests on py37/38 and mac/windows
    test:
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [macos-latest, windows-latest]
          python-version: [3.7, 3.8]

      steps:
        - name: Check out mitiq
          uses: actions/checkout@v2
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install Python dependencies
          run: |
            python -m pip install --upgrade pip
            make install requirements
        - name: Run the mitiq unit tests via pytest
          run: make test
