name: build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  # builds & tests the docs on py38
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out mitiq
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Set up conda
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          $CONDA/bin/conda env update --file environment.yml --name base
      - name: Install Python dependencies
        run: |
          eval "$(conda shell.bash hook)"
          conda activate base
          python -m pip install --upgrade pip
          make install requirements
          pip install -r docs/requirements.txt
      - name: Run the quilc & qvm Docker images
        run: |
          eval "$(conda shell.bash hook)"
          conda activate base
          docker run --rm -idt -p 5000:5000 rigetti/qvm -S
          docker run --rm -idt -p 5555:5555 rigetti/quilc -R

      - name: Build and test Sphinx docs
        run: |
          eval "$(conda shell.bash hook)"
          conda activate base
          make docs
          make doctest


