name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message:  'Hello @${{ github.actor }}, thank you for submitting a PR! We will respond as soon as possible, and if you have any questions in the meantime, you can ask us on the [Unitary Fund Discord](https://discord.unitary.fund).'
        issue-message: |
          Hello @${{ github.actor }}, thank you for your interest in Mitiq!
          If this is a bug report, please provide screenshots and/or **minimum viable code to reproduce your issue**,  so we can do our best to help get it fixed. If you have any questions in the meantime, you can also ask us on the [Unitary Fund Discord](https://discord.unitary.fund).