on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test pyquil with the qvm
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run root action with pip -e .[development] command
        uses: ./ # Uses an action in the root directory
        id: hello
      - name: Set up qvm and quilc with docker
        # run: echo "The time was ${{ steps.hello.outputs.time }}"
        run: |
          docker pull rigetti/qvm
          docker run --rm -idt -p 5000:5000 rigetti/qvm -S
          docker run --rm -idt -p 5555:5555 rigetti/quilc -R
          pip3 install pytest