on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to start qvm
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        # run: echo "The time was ${{ steps.hello.outputs.time }}"
        run: |
          docker pull rigetti/qvm
          docker run --rm -idt -p 5000:5000 rigetti/qvm -S
          docker run --rm -idt -p 5555:5555 rigetti/quilc -R
          pip3 install pytest