name: Docker Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [assigned, review_requested]

jobs:
  docker_job:
    runs-on: ubuntu-latest
    name: A job to test pyquil with the qvm
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run root action with pip -e .[development] command
        uses: ./ # Uses an action in the root directory
        id: qvm
      - name: Set up qvm and quilc with docker
        run: |
          docker pull rigetti/qvm
          qvm --version
#          docker run --rm -idt -p 5000:5000 rigetti/qvm -S
#          docker run --rm -idt -p 5555:5555 rigetti/quilc -R
#    - name: Test pyquil with pytest
#      run: |
#          chmod +x ./test_build.sh -tests-with-pyquil