# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Release Package to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    name: Build Mitiq distribution
    if: github.repository_owner == 'unitaryfund'
    runs-on: ubuntu-latest
    steps:
      - name: Check out mitiq
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies for build
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build mitiq
        run: python -m build
      - name: Store build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/*

  publish:
    name: Upload release to PyPi
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: pypi
      url: https://pypi.org/p/mitiq/
    permissions:
      id-token: write
    steps:
      - name: Fetch build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist/
      - name: Publish package distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
